# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842cc0a31246606d72b837db9ed61a6abccad48ed9253c5014588973d3d42ee036dac2a9cdfa551a57add77269b386e5622016e7afc1270d6667d7daa27ade74

test:
  secret_key_base: a5051834619f0213609b19cb711e0a71cae1353b8142aad6dd534505392368d7d7727aed14e02e16fa153384a1d13dc8f79c8de970ecf2843acbd04ec4d1abf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
